cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: ASIA3OVW6CNILA4AJKHJ
      secret-key: PLY87n8KkurwDVrKQ4K0b7DWVlsiFH5j6rJozMAl
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/787436409680/test
