cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: ASIA3OVW6CNIK7D46AB4
      secret-key: i8RsbXMg4cquOJL45LA6kWkNSY6PwIq8sjza+91z
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/787436409680/test
